config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'restaurants#index' # root que sea mostrar todos los restaurants
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: %w["chinese", "italian", "japanese", "french", "belgian"] }
  has_many :reviews, dependent: :destroy # dependent: :destroy que si se elimina un restaurante se eliminan sus reviews
end

app/models/review.rb
class Review < ApplicationRecord
  validates :content, :rating, presence: true
  validates :rating, inclusion: { in: 0..5}, numericality: { only_integer: true }
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [ :show ]
  # GET /restaurants
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: "Restaurant was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # GET /restaurants/new
  def new
    @restaurant = Restaurant.find(params[:restaurant_id]) # Debo encontrar el id
    # del restaurante al cual le crearemos la review
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(restaurant_params)

    if @review.save
      redirect_to @restaurant, notice: "Review was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  # Only allow a list of trusted parameters through.
  def restaurant_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container m-5">

  <h1>Restaurants</h1>
  <hr>

  <div id="restaurants">
    <ul>
      <% @restaurants.each do |restaurant| %>
        <li> <%= link_to restaurant.name, restaurant_path(restaurant) %> </li>
        <hr>
      <% end %>
    </ul>
  </div>

  <%= link_to "Create new restaurant", new_restaurant_path, class: 'btn btn-outline-primary' %>
</div>

app/views/restaurants/new.html.erb
<div class="container m-5">
  <h4>Create new restaurant</h4>
  <%= simple_form_for(@restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :category %>
    <%= f.submit "Create Restaurant", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/restaurants/show.html.erb
<div class="container show m-5">
  <h3><%= @restaurant.name %></h3>

  <hr>
  <h5>Address:</h5>
  <p class="info"><%= @restaurant.address %></p>

  <h5>Category:</h5>
  <p class="info"><%= @restaurant.category.capitalize %></p>

  <%= link_to "Create review", new_restaurant_review_path(@restaurant), class: "btn btn-outline-primary" %>

  <hr>

  <h5 class="mt-5">Reviews:</h5>

  <% @restaurant.reviews.each do |review| %>
    <div class="rating">
      <h6>Content: <%= review.content %></h6>
      <div class="d-flex">
        <% review.rating.times do %>
          <p>⭐</p>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/reviews/new.html.erb
<div class="container m-5">
  <h4>Create new review:</h4>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit "Create Review", class: "btn btn-primary" %>
  <% end %>
</div>